version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: sixmentor-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sixmentor
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3308:3306"  # on évite conflit avec un MySQL local
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    container_name: sixmentor-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sixmentor
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user

  frontend:
    build:
      context: ./frontend-angular
    container_name: sixmentor-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
